from python:3.9-slim

RUN apt-get update \
&& apt-get install gcc -y \
&& apt-get clean

COPY grafana_noti /app/grafana_noti/
COPY requirements.txt /app/

WORKDIR /app
EXPOSE 5000

RUN apt-get install gcc
RUN pip install -r /app/requirements.txt

CMD python -m grafana_noti.api